### ISSUE TITLE
Make UI changes

### ISSUE THREAD

**Issue by cjestavillo** [Sterling-Technologies/sterling-technologies.github.io#37]
- [x] link 'Schedule a Demo' button to 'Contact-Us' section (in E-commerce, Digital Marketing, Technology, Backoffice)
- [x] Added Case Studies section in homepage (before What We Use and after What We Do)
- [x] Added error and success message upon submitting the Contact Us form
- [x] Added Visit Site buttons in What We Do sections: Backoffice (Jobayan), Blockchain (Monico), Customer Support (Iristext and Chatbot)
- [x] Added image in Digital Marketing (after "AND SEO IS STILL A THING. WE DO IT WELL." tagline)
- [x] Make logos in What We Do: Technology section to donut chart, displaying its percentage

**Comment by cmagtalas** [comment]
Checked the following and it's okay:
- Schedule a Demo
- Added Case Studies
- Visit Site buttons
- Digital Marketing
- What We Do: Technology donut charts

Minor changes in 
- Error handling in the Contact Form:
![screen shot 2018-06-21 at 14 01 39](https://user-images.githubusercontent.com/33407114/41700713-000d43b2-755c-11e8-8765-be8e54dbb227.png)

**Comment by cjestavillo** [comment]
Changes had been made.
![image](https://user-images.githubusercontent.com/33796130/41701544-6b957110-755f-11e8-98a2-4d019ed48c05.png)

**Comment by cmagtalas** [comment]
Thanks Ciara. Please deploy to live.

**Comment by cmagtalas** [comment]
Good in production. Closing this ticket.
<img width="520" alt="screen shot 2018-06-21 at 3 01 44 pm" src="https://user-images.githubusercontent.com/33407114/41702834-10157344-7564-11e8-80bd-bb032ba4bb53.png">
